name: Deploy

on:
  push:
    branches:
      - master
      
  
jobs:
      
  deploy:
    runs-on: [ubuntu-latest, node16]
  
    steps:
      - uses: actions/checkout@v2

      - name: Deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            # Copy and build new version
            git checkout master
            git fetch --all
            git reset --hard origin/master
            yarn install
            yarn build
            pm2 kill
            pm2 start "npm run start" --name App
